FROM osixia/phpldapadmin:0.9.0

#维护者信息
MAINTAINER bfire<bfire2013@gmail.com>

ENV PHPLDAPADMIN_HTTPS false
ENV PHPLDAPADMIN_LDAP_HOSTS 72mao.com 

RUN echo "alias ll='ls -laF --color=auto'" >> ~/.bashrc