FROM osixia/phpldapadmin:0.9.0

#维护者信息
MAINTAINER StevenAn<alz8888@qq.com>

ENV PHPLDAPADMIN_HTTPS false
ENV PHPLDAPADMIN_LDAP_HOSTS 72mao.com 

RUN echo "alias ll='ls -laF --color=auto'" >> ~/.bashrc